"""Initial migration

Revision ID: 91b251abd345
Revises: 
Create Date: 2023-09-21 15:40:40.705966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91b251abd345'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comprador',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('contacto', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehiculo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('propietario_nombre', sa.String(length=100), nullable=False),
    sa.Column('propietario_direccion', sa.String(length=200), nullable=False),
    sa.Column('propietario_correo', sa.String(length=100), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('chasis', sa.String(length=50), nullable=False),
    sa.Column('motor', sa.String(length=50), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('clase_vehiculo', sa.String(length=50), nullable=False),
    sa.Column('tipo_vehiculo', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('fecha_matricula', sa.DateTime(), nullable=False),
    sa.Column('fecha_ultima_revision', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chasis'),
    sa.UniqueConstraint('motor'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('vendedor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('correo_electronico', sa.String(length=100), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo_electronico')
    )
    op.create_table('venta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('comprador_id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('precio_venta', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['comprador_id'], ['comprador.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ganancia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ganancia')
    op.drop_table('venta')
    op.drop_table('vendedor')
    op.drop_table('vehiculo')
    op.drop_table('comprador')
    # ### end Alembic commands ###
